services:
  - type: web
    name: innovex-techno-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24
